on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: windows-latest
    permissions: read-all

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore Dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

  publish:
    runs-on: windows-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    permissions: write-all
    env:
      VER_TAG: ${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Publish & Pack
      run: |
        New-Item -Path ListenAI.Factory.FirmwareDeploy\bin\Publish -ItemType Directory
        dotnet publish -c Release -r win-x64 -f net6.0-windows --no-self-contained -p:PublishSingleFile=true
        Remove-Item -Path ListenAI.Factory.FirmwareDeploy\bin\Release\net6.0-windows\win-x64\publish\*.pdb -Force
        Copy-Item ListenAI.Factory.FirmwareDeploy\bin\Release\net6.0-windows\win-x64\publish -Destination ListenAI.Factory.FirmwareDeploy\bin\Publish\win-x64 -Recurse
        dotnet publish -c Release -r win-x86 -f net6.0-windows --no-self-contained -p:PublishSingleFile=true
        Remove-Item -Path ListenAI.Factory.FirmwareDeploy\bin\Release\net6.0-windows\win-x86\publish\*.pdb -Force
        Copy-Item ListenAI.Factory.FirmwareDeploy\bin\Release\net6.0-windows\win-x86\publish -Destination ListenAI.Factory.FirmwareDeploy\bin\Publish\win-x86 -Recurse
        Compress-Archive -Path ListenAI.Factory.FirmwareDeploy\bin\Publish\* -DestinationPath ListenAI.Factory.FirmwareDeploy\bin\${Env:VER_TAG}.zip

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ListenAI.Factory.FirmwareDeploy/bin/${{ github.ref_name }}.zip"
        bodyFile: "RELEASE"
        draft: true
        tag: ${{ github.ref_name }}
